# Generated by Django 5.0.6 on 2024-08-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0004_alunos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='professores',
            name='imagem',
            field=models.FileField(null=True, upload_to='imagem_professores'),
        ),
    ]
