# Generated by Django 5.1 on 2024-08-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0006_admins_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='eletivas',
            name='link',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
