# Generated by Django 5.1 on 2024-08-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0009_alter_anuncio_descricao_alter_anuncio_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgCarrossel',
        ),
        migrations.AddField(
            model_name='professores',
            name='descricao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professores',
            name='professor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='professores',
            name='tutor',
            field=models.BooleanField(null=True),
        ),
    ]
