# Generated by Django 5.0.6 on 2024-09-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0010_delete_imgcarrossel_professores_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='descricao',
            field=models.TextField(max_length=127),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
    ]
