# Generated by Django 5.0.6 on 2024-09-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0011_alter_anuncio_descricao_alter_anuncio_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eletivas',
            name='img_professores_eletiva',
            field=models.ImageField(null=True, upload_to='img_eletivas/img_professores_eletiva'),
        ),
    ]
