# Generated by Django 5.0.6 on 2024-08-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0002_anuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='acoes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imgcarrossel',
            name='img1',
            field=models.FileField(upload_to='img_carrosssel/'),
        ),
        migrations.AlterField(
            model_name='imgcarrossel',
            name='img2',
            field=models.FileField(upload_to='img_carrosssel/'),
        ),
        migrations.AlterField(
            model_name='imgcarrossel',
            name='img3',
            field=models.FileField(upload_to='img_carrosssel/'),
        ),
    ]
